<MyLayout>
    id: my_widget
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        padding: 50
        spacing: 20

        FileChooserIconView:
            id: filechooser
            on_selection: my_widget.selected(filechooser.selection)

        Button:
            id: button
            size:(80,80)
            text: start
            on_press: my_widget.on_click()
